name: "publish-github-to-hashnode"
author: "Jack Linke"
description: "Publish Posts from a GitHub repository to a Hashnode Publication."
branding:
  icon: "edit-3"
  color: "green"

inputs:
  added-files:
    description: "The list of added files in the repository."
    required: true
  changed-and-modified-files:
    description: "The list of changed or modified files in the repository."
    required: true
  deleted-files:
    description: "The list of deleted files in the repository."
    required: true
  access-token:
    description: "Your Hashnode API Personal Access Token. See: https://hashnode.com/settings/developer"
    required: true
  publication-host:
    description: "The publication host (e.g., blog.mydomain.com)."
    required: true
  posts-directory:
    description: "The local directory containing the blog posts, if different from the root directory."
    required: false
    default: "posts"

outputs:
  result_json:
    description: "Publish result as a JSON string"
  result_summary:
    description: "Publish result summary formatted as text"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    ACCESS_TOKEN: ${{ inputs.access-token }}
    POSTS_DIRECTORY: ${{ inputs.posts-directory }}
    PUBLICATION_HOST: ${{ inputs.publication-host }}
    ADDED_FILES: ${{ inputs.added-files }}
    CHANGED_AND_MODIFIED_FILES: ${{ inputs.changed-and-modified-files }}
    DELETED_FILES: ${{ inputs.deleted-files }}
    PYTHONUNBUFFERED: "1"
  args:
    - ${{ inputs.access-token }}
    - ${{ inputs.posts-directory }}
    - ${{ inputs.publication-host }}
    - ${{ inputs.added-files }}
    - ${{ inputs.changed-and-modified-files }}
    - ${{ inputs.deleted-files }}
